export const SECTORS = [
  "AI & Machine Learning",
  "Fintech",
  "Healthtech",
  "Edtech",
  "Cleantech",
  "Deep Tech",
  "Consumer",
  "SaaS / B2B Software",
  "Marketplace",
  "Govtech",
  "Agritech",
  "Proptech",
  "Legaltech",
  "Media & Creative",
  "Social Impact",
  "Future of Work",
  "Cybersecurity",
  "Web3 & Crypto",
  "Hardware & IoT",
  "Space Tech",
  "Marinetech",
] as const;

export const SECTOR_HIERARCHY: Record<string, string[]> = {
  "AI & Machine Learning": ["Generative AI", "Computer Vision", "NLP", "ML Infrastructure"],
  "Fintech": ["Payments", "Banking & Lending", "Insurtech", "RegTech", "Crypto & DeFi"],
  "Healthtech": ["Digital Health", "Medtech", "Mental Health", "Biotech", "Health Data"],
  "Cleantech": ["Climate Tech", "Energy Storage", "Carbon Markets", "Sustainable Agriculture", "Circular Economy"],
  "Deep Tech": ["Robotics", "Quantum Computing", "Semiconductors", "Photonics"],
  "SaaS / B2B Software": ["Developer Tools", "HR Tech", "Sales Tech", "Data & Analytics", "Security SaaS"],
};

export const ALL_SUBSECTORS: string[] = Object.values(SECTOR_HIERARCHY).flat();

export const UK_LOCATIONS = [
  "London",
  "Manchester",
  "Bristol",
  "Birmingham",
  "Edinburgh",
  "Glasgow",
  "Leeds",
  "Cambridge",
  "Oxford",
  "Liverpool",
  "Newcastle",
  "Sheffield",
  "Nottingham",
  "Cardiff",
  "Belfast",
  "Exeter",
  "Brighton",
  "Bath",
  "Southampton",
  "Coventry",
  "Aberdeen",
  "Dundee",
  "York",
  "Reading",
] as const;

export const EUROPEAN_COUNTRIES = [
  "UK",
  "Germany",
  "France",
  "Netherlands",
  "Sweden",
  "Spain",
  "Ireland",
  "Denmark",
  "Finland",
  "Norway",
  "Switzerland",
  "Belgium",
  "Portugal",
  "Italy",
  "Estonia",
  "Poland",
  "Czech Republic",
  "Austria",
] as const;

/** lat/lng lookup for distance calculations (Haversine). Add cities as needed. */
export const CITY_COORDINATES: Record<string, [number, number]> = {
  London: [51.5074, -0.1278],
  Manchester: [53.4808, -2.2426],
  Bristol: [51.4545, -2.5879],
  Birmingham: [52.4862, -1.8904],
  Edinburgh: [55.9533, -3.1883],
  Glasgow: [55.8642, -4.2518],
  Leeds: [53.8008, -1.5491],
  Cambridge: [52.2053, 0.1218],
  Oxford: [51.752, -1.2577],
  Liverpool: [53.4084, -2.9916],
  Newcastle: [54.9783, -1.6178],
  Sheffield: [53.3811, -1.4701],
  Nottingham: [52.9548, -1.1581],
  Cardiff: [51.4816, -3.1791],
  Belfast: [54.5973, -5.9301],
  Exeter: [50.7184, -3.5339],
  Brighton: [50.8225, -0.1372],
  Bath: [51.3781, -2.3597],
  Southampton: [50.9097, -1.4044],
  Coventry: [52.4068, -1.5197],
  Aberdeen: [57.1497, -2.0943],
  Dundee: [56.462, -2.9707],
  York: [53.959, -1.0815],
  Reading: [51.4543, -0.9781],
  Berlin: [52.52, 13.405],
  Munich: [48.1351, 11.582],
  Hamburg: [53.5753, 10.0153],
  Frankfurt: [50.1109, 8.6821],
  Paris: [48.8566, 2.3522],
  Amsterdam: [52.3676, 4.9041],
  Stockholm: [59.3293, 18.0686],
  Madrid: [40.4168, -3.7038],
  Barcelona: [41.3851, 2.1734],
  Dublin: [53.3498, -6.2603],
  Copenhagen: [55.6761, 12.5683],
  Helsinki: [60.1699, 24.9384],
  Oslo: [59.9139, 10.7522],
  Zurich: [47.3769, 8.5417],
  Brussels: [50.8503, 4.3517],
  Lisbon: [38.7223, -9.1393],
  Milan: [45.4654, 9.1866],
  Tallinn: [59.437, 24.7536],
  Warsaw: [52.2297, 21.0122],
  Prague: [50.0755, 14.4378],
  Vienna: [48.2082, 16.3738],
};

export const CITIES_BY_COUNTRY: Record<string, string[]> = {
  UK: ["London", "Manchester", "Bristol", "Birmingham", "Edinburgh", "Glasgow", "Leeds", "Cambridge", "Oxford", "Liverpool", "Newcastle", "Sheffield", "Nottingham", "Cardiff", "Belfast", "Exeter", "Brighton", "Bath", "Southampton", "Coventry", "Aberdeen", "Dundee", "York", "Reading"],
  Germany: ["Berlin", "Munich", "Hamburg", "Frankfurt", "Cologne", "Stuttgart"],
  France: ["Paris", "Lyon", "Marseille", "Toulouse", "Bordeaux"],
  Netherlands: ["Amsterdam", "Rotterdam", "The Hague", "Eindhoven"],
  Sweden: ["Stockholm", "Gothenburg", "Malmö"],
  Spain: ["Madrid", "Barcelona", "Valencia", "Bilbao"],
  Ireland: ["Dublin", "Cork", "Galway"],
  Denmark: ["Copenhagen"],
  Finland: ["Helsinki", "Tampere", "Oulu"],
  Norway: ["Oslo", "Bergen"],
  Switzerland: ["Zurich", "Geneva", "Basel"],
  Belgium: ["Brussels", "Antwerp", "Ghent"],
  Portugal: ["Lisbon", "Porto"],
  Italy: ["Milan", "Rome", "Turin", "Florence"],
  Estonia: ["Tallinn", "Tartu"],
  Poland: ["Warsaw", "Kraków", "Wrocław", "Poznań"],
  "Czech Republic": ["Prague", "Brno"],
  Austria: ["Vienna", "Graz"],
};

export const CURRENCY_SYMBOLS: Record<string, string> = {
  GBP: "£",
  EUR: "€",
  USD: "$",
  SEK: "SEK ",
  NOK: "NOK ",
  CHF: "CHF ",
  DKK: "DKK ",
  PLN: "PLN ",
};

export const COUNTRY_CURRENCY: Record<string, string> = {
  UK: "GBP",
  Germany: "EUR",
  France: "EUR",
  Netherlands: "EUR",
  Sweden: "SEK",
  Spain: "EUR",
  Ireland: "EUR",
  Denmark: "DKK",
  Finland: "EUR",
  Norway: "NOK",
  Switzerland: "CHF",
  Belgium: "EUR",
  Portugal: "EUR",
  Italy: "EUR",
  Estonia: "EUR",
  Poland: "PLN",
  "Czech Republic": "EUR",
  Austria: "EUR",
};

export const STAGE_LABELS: Record<string, string> = {
  PRE_IDEA: "Pre-idea",
  PRE_SEED: "Pre-seed",
  SEED: "Seed",
  SERIES_A: "Series A",
  SERIES_B_PLUS: "Series B+",
  ANY: "Any stage",
};

export const TYPE_LABELS: Record<string, string> = {
  ACCELERATOR: "Accelerator",
  VENTURE_STUDIO: "Venture Studio",
  VC: "VC",
  ANGEL_NETWORK: "Angel Network",
  INCUBATOR: "Incubator",
  GRANT: "Grant",
};

export const TYPE_COLORS: Record<string, string> = {
  ACCELERATOR: "bg-indigo-500/10 text-indigo-400 border-indigo-500/20",
  VENTURE_STUDIO: "bg-purple-500/10 text-purple-400 border-purple-500/20",
  VC: "bg-blue-500/10 text-blue-400 border-blue-500/20",
  ANGEL_NETWORK: "bg-amber-500/10 text-amber-400 border-amber-500/20",
  INCUBATOR: "bg-teal-500/10 text-teal-400 border-teal-500/20",
  GRANT: "bg-green-500/10 text-green-400 border-green-500/20",
};
