name: Seed database

on:
  workflow_dispatch:

jobs:
  seed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - run: npx prisma db push
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
      - run: npm run db:seed
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
      - run: npm run db:seed-full
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
